# Activar junto a mysql: --spring.profiles.active=mysql,eureka
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:false}
    instance-id: ${spring.application.name}:${server.port}
    status-page-url-path: /swagger-ui/index.html
    home-page-url-path: /swagger-ui/index.html
    health-check-url-path: /api/usuarios
    lease-renewal-interval-in-seconds: 10
